### PR TITLE
Change setup and workflows for this project

### PR DESCRIPTION
**Pull request by wbarnha**

### CODE REVIEW

**Comment by wbarnha** [comment]
I've decided to go ahead and activate the job that allows us to automatically upload builds to PyPi. We'll need to define `PYPI_API_TOKEN` in this repo's secrets, @patkivikram.

**Comment by wbarnha** [comment]
On second thought- do we want really want to release as v0.9.0 and not v0.8.1?

**Comment by austinnichols101** [comment]
> 

there has already been a 0.8.1 release (0.8.6 is the latest release).

**Comment by wbarnha** [comment]
> > 
> 
> there has already been a 0.8.1 release (0.8.6 is the latest release).

I'm a bit confused by this statement. I understand the latest release of faust-streaming is 0.8.6, whereas `faust-streaming/python-rocksdb` is v0.8.0

**Comment by patkivikram** [comment]
> I've decided to go ahead and activate the job that allows us to automatically upload builds to PyPi. We'll need to define `PYPI_API_TOKEN` in this repo's secrets, @patkivikram.

Sure go ahead and do that. Do you need anything from my end? On a similar note could we do something similar for faust-streaming?

**Comment by wbarnha** [comment]
> > I've decided to go ahead and activate the job that allows us to automatically upload builds to PyPi. We'll need to define `PYPI_API_TOKEN` in this repo's secrets, @patkivikram.
> 
> Sure go ahead and do that. Do you need anything from my end? On a similar note could we do something similar for faust-streaming?

I don't have access to either repositories as a maintainer, so either I'll need authorization to add a token or you'll need to do it.

**Comment by wbarnha** [comment]
I'd also like to tag the initial release as `v0.8.1rc1` or `v0.9.0rc1` in case something goes awry.

**Comment by wbarnha** [comment]
Hold off on merging, there's a bug hidden in the upload job.

**Comment by wbarnha** [comment]
Fixed the build jobs, but I need to make sure that my own upload jobs run.

**Comment by wbarnha** [comment]
It builds usable wheel files now, but each wheel file is 66 MB... https://test.pypi.org/manage/project/faust-streaming-rocksdb/release/0.9.0rc2/

Meanwhile the sdist is 270 kB, and unusable. Yuck.

**Comment by wbarnha** [comment]
Never mind, the sdist is good to go! I was erronously using `--no-deps` when running pip install.

**Pull request merged**
