### PR TITLE
Major update with changes from other python-rocksdb forks

### PR DESCRIPTION
**Pull request by wbarnha**
Credit goes to @NightTsarina, and many others, for aggregating and maintaining all these commits!

Upon further review, I'll need to edit a few things before we can merge this. Things like the README, and build workflows aren't identical to what's configured for this repo.

### CODE REVIEW

**Comment by patkivikram** [comment]
Can you please fix the conflicts?

**Comment by patkivikram** [comment]
@wbarnha do you want to do a release to pypi? I can add you as a maintainer to this repo

**Comment by wbarnha** [comment]
Sure, I'll do a release on PyPi later today. Please add me as a maintainer when you get the opportunity.

**Comment by patkivikram** [comment]
what is your pypi id?

**Comment by wbarnha** [comment]
My ID on PyPi is also `wbarnha`

**Pull request merged**
